apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: YWRtaW4= # user name has to be base64 encoded
  mongo-password: YWRtaW4= # password has to be base64 encoded